import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_disaster_alert(
    sender_email,
    sender_password,
    receiver_email,
    disaster_type,
    final_confidence,
    image_prediction,
    image_confidence,
    text_prediction,
    text_confidence,
    user_text
):
    subject = f"🚨 Emergency Alert: {disaster_type} Detected"

    body = f"""
Dear Authority,

This is an automated emergency notification generated by the Multimodal Disaster Alert System.

A possible disaster has been detected with high confidence.

Disaster Details:
-----------------
Final Prediction: {disaster_type}
Final Confidence: {final_confidence}%

Image Model Prediction: {image_prediction}
Image Confidence: {image_confidence}%

Text Model Prediction: {text_prediction}
Text Confidence: {text_confidence}%

Reported Text:
--------------
{user_text}

Recommended Action:
-------------------
Please verify the situation immediately and take necessary emergency response action.

Regards,
Multimodal Disaster Alert System
"""

    message = MIMEMultipart()
    message["From"] = sender_email
    message["To"] = receiver_email
    message["Subject"] = subject

    message.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(message)
        server.quit()

        return True, "Email alert sent successfully."

    except Exception as e:
        return False, str(e)